// Converts a plain-text ASCII art file into a React component that renders it as
// a single inlined SVG <path>. Run manually (`npm run ascii:build`) — not part of
// `next build`. See CLAUDE.md / the plan for why: this trades a client-dependent
// monospace-font render (which distorts differently per OS/browser) for a fixed
// vector shape baked in ahead of time, while keeping `fill="currentColor"` so the
// art still follows the site's light/dark accent color like plain text did.
//
// Font is read directly from the local system (DejaVu Sans Mono, commonly
// preinstalled on Linux) purely as a one-time source for glyph outlines — the
// font file itself is never copied into the repo or shipped to the browser,
// only the resulting vector paths for the specific art below are.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf";
const FONT_SIZE = 100;
const LINE_HEIGHT = 110;
const PAD = 10;

function loadFont(fontPath) {
  const buf = fs.readFileSync(fontPath);
  const arrayBuffer = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
  return opentype.parse(arrayBuffer);
}

function generate({ sourceFile, outFile, componentName }) {
  const font = loadFont(FONT_PATH);
  const text = fs.readFileSync(sourceFile, "utf8").replace(/\n$/, "");
  const lines = text.split("\n");

  const combined = new opentype.Path();
  let maxWidth = 0;
  lines.forEach((line, i) => {
    const y = PAD + (i + 1) * LINE_HEIGHT;
    combined.extend(font.getPath(line, 0, y, FONT_SIZE));
    const w = font.getAdvanceWidth(line, FONT_SIZE);
    if (w > maxWidth) maxWidth = w;
  });

  const viewWidth = Math.ceil(maxWidth + PAD * 2);
  const viewHeight = Math.ceil(lines.length * LINE_HEIGHT + PAD * 2);
  const d = combined.toPathData(2);

  const relSource = path.relative(path.join(__dirname, "../.."), sourceFile);
  const jsx = `// AUTO-GENERATED by scripts/ascii-svg/generate.mjs — do not edit by hand.
// Source: ${relSource}
// Regenerate with: npm run ascii:build

export function ${componentName}({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 ${viewWidth} ${viewHeight}" className={className} fill="currentColor" aria-hidden="true">
      <path d="${d}" />
    </svg>
  );
}
`;

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, jsx);
  console.log(`wrote ${path.relative(process.cwd(), outFile)} (viewBox 0 0 ${viewWidth} ${viewHeight}, ${lines.length} lines)`);
}

const artPieces = [
  {
    sourceFile: path.join(__dirname, "source/ai-obs-eye.txt"),
    outFile: path.join(__dirname, "../../components/projects/ascii/AiObsEyeSvg.tsx"),
    componentName: "AiObsEyeSvg",
  },
  {
    sourceFile: path.join(__dirname, "source/neuraldbg-neuron.txt"),
    outFile: path.join(__dirname, "../../components/projects/ascii/NeuraldbgNeuronSvg.tsx"),
    componentName: "NeuraldbgNeuronSvg",
  },
  {
    sourceFile: path.join(__dirname, "source/devops-lab-motif.txt"),
    outFile: path.join(__dirname, "../../components/projects/ascii/DevopsLabMotifSvg.tsx"),
    componentName: "DevopsLabMotifSvg",
  },
  {
    sourceFile: path.join(__dirname, "source/lab-flask.txt"),
    outFile: path.join(__dirname, "../../components/lab/ascii/LabFlaskSvg.tsx"),
    componentName: "LabFlaskSvg",
  },
];

for (const piece of artPieces) generate(piece);
