apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: portfolio
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: "200m"
              memory: "384Mi"
            limits:
              cpu: "1000m"
              memory: "768Mi"
